Develop a CRM script to handle import name mis matches
conda-incubator/conda-recipe-manager pull request #218
Opened 2024-10-25 21:01 UTC by schuylermartin45

Resolves #181 

The original ticket concept has changed a few times as others have pointed me to the `cf-graph-countyfair` data project.

We now cache a modified version of Conda Forge's mapping that attempts to map irregular cases where the "import name" does not match the package name.

In theory, this will make our Python dependency calculation efforts more accurate.

2024-10-25 21:12 UTC, schuylermartin45 commented
I'm unclear on the licensing implications of this change. I wouldn't consider the data derived from Conda Forge here as "source code", but I'm not sure what the legal interpretation of "source code" is over my engineering interpretation.

That being said, I'm guessing we want to give some kind of attribution.

I imagine this goes one of two routes:

1) Copy what we did in `conda-recipe-manager-test-data`, and modify the top of the LICENSE file in this repo to include:
```
Copyright (c) 2016-2018, conda-forge
Copyright (c) 2016-2018, conda-forge contributors
```
I'm guessing we could end in `2024` over `2018`, but `2018` is the most recent listed in their LICENSE file.

2) Copy the names actually found in `cf-graph-countyfair`: 
```
Copyright (c) 2018, Board of Trustees of Columbia University in the city of New York.
Copyright (c) 2017, Peter M. Landwehr
Copyright (c) 2017, Anthony Scopatz
Copyright (c) 2016 Aaron Meurer, Gil Forsyth
```
I imagine this file is very out of date and there have been many contributors post `2018` on the project not captured here.

@jezdez @beeankha Thoughts?

2024-10-25 22:03 UTC, beckermr requested changes
A more direct comment related to this PR. 

You should depend directly on `conda-forge-metadata` to get these mappings. 

See the APIs we supply here: https://github.com/conda-forge/conda-forge-metadata/blob/main/conda_forge_metadata/autotick_bot/pypi_to_conda.py#L33


`conda-forge-metadata` is available on [pypi](https://pypi.org/project/conda-forge-metadata/#description) and OFC conda-forge. 

If there is another API you want/need, we should add it in conda-forge-metadata.

2024-10-28 15:04 UTC, beckermr commented
Ah cool. That's all fine. In any case, the url you are using is not a supported api and could break. We should add an api to conda-forge-metadata to pull the file you need if it is not there.

2024-10-28 15:29 UTC, beckermr commented
> As far as I know, none of this is documented or explained anywhere. 

Yep, this is a big hole. We've not been able to close it yet and that is definitely largely my fault. The hope is that as we add more to conda-forge-metadata, we will add documentation and this will be the place to look.

Thank you for your patience!

2024-10-28 19:46 UTC, schuylermartin45 commented
Even if it is in an API, I'd still like to locally cache the results. Maybe it comes from my personal bias working in the IoT and firmware space, but network calls have costs. I'd rather not incur API hits on data that appears to change pretty infrequently.

So even if this ends up on `conda-forge-metadata`, I'll want some local form for redundancy and speed.

I'm not sure how long/if I have the time to add this to `conda-forge-metadata` but I'll try to at least look. This PR might be a stop gap for our more immediate needs.

At the very least, I'm going to make a note at the top of the script indicating that the `conda-forge-metadata` API exists and we should consider using it in the future. Glad we talked through this!

2024-10-28 20:00 UTC, schuylermartin45 commented
Ok, so it is at least partially implemented: [def map_import_to_package(import_name: str) -> str:
](https://github.com/conda-forge/conda-forge-metadata/blob/18af7dc39d37ccdc5dc3a13f91ffcddfd7cee36d/conda_forge_metadata/autotick_bot/import_to_pkg.py#L104)

But obviously I'd have to query every single string. The table this PR generates for the cache is only ~300kb, but I'd imagine we'd want some pagination scheme to future-proof, if we allow for a fully query of the mapping.

2024-10-28 20:11 UTC, schuylermartin45 commented
I collected my thoughts together and opened this against `conda-forge-metadata`: https://github.com/conda-forge/conda-forge-metadata/issues/55

2024-10-28 20:11 UTC, beckermr commented
We can add an API to the file `import_name_priority_mapping.json` you are using. That file is made from the underlying mapping results from each package with some graph heuristics applied to resolve conflicts.

2024-11-14 19:37 UTC, jezdez commented
> I'm unclear on the licensing implications of this change. I wouldn't consider the data derived from Conda Forge here as "source code", but I'm not sure what the legal interpretation of "source code" is over my engineering interpretation.
> 
> That being said, I'm guessing we want to give some kind of attribution.
> 
> I imagine this goes one of two routes:
> 
> 1. Copy what we did in `conda-recipe-manager-test-data`, and modify the top of the LICENSE file in this repo to include:
> 
> ```
> Copyright (c) 2016-2018, conda-forge
> Copyright (c) 2016-2018, conda-forge contributors
> ```
> 
> I'm guessing we could end in `2024` over `2018`, but `2018` is the most recent listed in their LICENSE file.
> 
> 2. Copy the names actually found in `cf-graph-countyfair`:
> 
> ```
> Copyright (c) 2018, Board of Trustees of Columbia University in the city of New York.
> Copyright (c) 2017, Peter M. Landwehr
> Copyright (c) 2017, Anthony Scopatz
> Copyright (c) 2016 Aaron Meurer, Gil Forsyth
> ```
> 
> I imagine this file is very out of date and there have been many contributors post `2018` on the project not captured here.
> 
> @jezdez @beeankha Thoughts?

I concur what @beckermr said above, it would be easiest to follow what https://github.com/conda-forge/conda-forge-metadata/issues/55 is proposing, not just for legal but also for API stability reasons.

Once it's exposed, spelling out licensing information for the data becomes moot, not needed anymore, since the license of conda-forge-metadata  [is encoded in the package metadata](https://github.com/conda-forge/conda-forge-metadata/blob/0ea51d7a70a3b62ce04e3b4e29ff0519b3f85391/pyproject.toml#L23). And importing the data via Python is a legally safe thing to do.

Of course, if you add any file from any repo, it's easiest to copy the full `LICENSE` file (or equivalent like `COPYING`) of the 3rd party repo into the `LICENSE` file of this repo, with a headline noting where it came from, like https://github.com/regro/cf-graph-countyfair/blob/master/License actually does as well. That way it becomes clear that there are components included here that are derived from other permissively licensed software. I've also seen separate `LICENSE` with a suffix being used successfully to express more complex licensing setups and simply referencing them in a central `LICENSE` file, e.g. a `LICENSE.cf-graph-countyfair` that is referenced in `LICENSE`.

2024-11-14 19:39 UTC, jezdez commented
Of course the usual thing applies, I'm not a lawyer or licensing expert, and I'd encourage to reach out to Anaconda legal or NumFOCUS legal to get confirmation.

2026-06-06 05:20 UTC, closed without merging